// Node: Report Generator
// Produces a structured client-facing markdown investment brief.

import { State } from "../state";
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";

const getLLM = () => new ChatGoogleGenerativeAI({ model: "gemini-2.0-flash", temperature: 0.1 });

export const reportGenerator = async (state: State): Promise<Partial<State>> => {
  const llm = getLLM();
  const resolvedName = state.companyInfo?.name || state.companyInput;
  const date = new Date().toISOString().split("T")[0];

  const fullResearchPackage = JSON.stringify(
    {
      companyInfo: state.companyInfo,
      synthesis: {
        synthesisScore: state.scores?.weightedTotal,
        investThesis: state.investThesis,
        watchFor: state.watchFor,
        comparableTo: state.comparableTo,
        ...state.synthesis
      },
      scores: state.scores,
    },
    null,
    2
  );

  const prompt = `Report Generator:

You are a senior equity research analyst writing a client-facing investment brief. Using all research data, write a structured markdown report.

Data:
${fullResearchPackage}

Write the report in this EXACT structure:

# ${resolvedName} — Investment Research Brief

## Verdict: ${state.verdict} (${state.confidence || 50}% confidence)
> ${state.headline || "Investment Analysis Complete"}

## Company Snapshot
[2-3 sentences: what they do, where they operate, stage of business]

## Investment Thesis
[3-4 sentences making the core case for or against]

## Scorecard
| Dimension | Score | Weight | Weighted |
|-----------|-------|--------|---------|
| Growth | X/10 | 25% | X.X |
| Moat | X/10 | 20% | X.X |
| Financial Health | X/10 | 25% | X.X |
| Sentiment | X/10 | 15% | X.X |
| Valuation | X/10 | 15% | X.X |
| **Total** | | | **X.X/10** |

## Key Strengths
- Strength 1
- Strength 2
- Strength 3

## Key Risks
- Risk 1
- Risk 2
- Risk 3

## What to Watch
[2-3 triggers that would change this verdict]

## Analyst Note
[1-2 sentences of honest uncertainty or caveats about data quality]

---
*Research generated by AI Investment Agent · ${date} · For informational purposes only*

Write in a professional but direct tone. No fluff. Every sentence must add information.`;

  const result = await llm.invoke(prompt);

  return {
    report: result.content as string,
    streamLog: [`✅ Report Generated`],
  };
};
